apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
  namespace: group4
spec:
  entrypoint: hello

  templates:
  - name: hello
    steps:
    - - name: hello
        template: print-message
        arguments:
          parameters: [{name: message, value: "hello1"}]
      

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.message}}"]