apiVersion: apps/v1
kind : Deployement
metadata:
  name: manual-test
  namespace: group4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manual-test
template:
  metadata:
    labels:
      app: manual-test
  spec:
    securityContext:
      runAsUser: 1000
      runAsGroup : 1000
    containers:
    - name: manual-test
      command: ["sleep", "infinity"]
      image: ubuntu
      imagePullPolicy: Always
      columeMounts:
      - name: gis-data
        mountPath : /data
      resources: {}
    volumes:
    - name: gis-data
      persistentVolumeClaim:
        claiName : gis-pvc