apiVersion: batch/v1
kind: Job
metadata:
  name: extract
  namespace: group4
spec:
  template:
    spec:
      containers:
      - name: extract
        image: mwendler/wget:latest
        command: ["sh", "-c"]
        args: ["mkdir -p /mount_path/extraction && \
                wget -O ./mount_path/extraction/companies-march-2025.geojson --no-check-certificate https://dataworks.calderdale.gov.uk/download/emg4m/62p/companies-march-2025.geojson"]
        volumeMounts:
          - name: fuse-gis-group4
            mountPath: /mount_path
      restartPolicy: Never
      volumes:
        - name: fuse-gis-group4