apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: map-reduce-workflow-template
  namespace: group4

spec:
  entrypoint: tileset-workflow

  arguments:
    parameters:
      - name: url

  templates:
  - name: tileset-workflow
    steps:
      - - name: extract-geojson
          template: extract-geojson
          arguments: {}
      - - name: transform-geojson
          template: transform-geojson
          arguments: {}
  
  - name: extract-geojson
    container:
      name: main
      image: curlimages/curl:latest
      command: ["sh", "-c"]
      args: ["mkdir -p /data/extraction && \
              curl -o /data/extraction/companies-march-2025.geojson {{workflow.parameters.url}}"]
      resources: {}
      volumeMounts:
        - name: gis-pvc
          mountPath: /data
    restartPolicy: Never
    volumes:
      - name: gis-pvc
        persistentVolumeClaim:
          claimName : gis-pvc
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
  
  - name: transform-geojson
    container:
      image: europe-west1-docker.pkg.dev/mptc-external-1/cs2025/tippecanoe-group4:latest
      command: ["sh", "-c"]
      args: ["mkdir -p /data/transformation && \
              tippecanoe -r1 --read-parallel --drop-densest-as-needed --extend-zooms-if-still-dropping -zg --output=/data/transformation/companies-group4.mbtiles --force /data/extraction/companies-march-2025.geojson"]
      volumeMounts:
        - name: gis-pvc
          mountPath: /data
    restartPolicy: Never
    volumes:
      - name: gis-pvc
        persistentVolumeClaim:
          claimName : gis-pvc
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

  
